server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers:  localhost:9092

kafka-topic:
  name: sm-test-topic-1
  partitions: 3
  replication-factor: 1


# Use t
#spring:
#  kafka:
#    producer:
#      bootstrap-servers:  localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer